BBP_PKT_STX = 0x3D

BBP_PKT_IDX_FLAG = 1
BBP_LPKT_IDX_LENGTH = 4
BBP_LPKT_IDX_CRC8 = 6
BBP_LPKT_IDX_TGT_ADDR = 7
BBP_LPKT_IDX_SRC_ADDR = 9
BBP_LPKT_IDX_CONTENT = 11

BBP_SPKT_IDX_LENGTH = 2
BBP_SPKT_IDX_CRC8 = 3
BBP_SPKT_IDX_TYPE = 4
BBP_SPKT_IDX_CONTENT=5
